#################################3
# Site settings

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: false
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  per_page: 5

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

#kramdown:
#  parse_block_html: true

plugins:
  #- jekyll-paginate-v2

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - "*.swo"
  - "*.swp"
  - "*.bak"
  - ".DS_Store"


#################################3
title: Authored-In-Exile
description: Blog for comics
baseurl: 
url: https://authoredinexile.github.io

# Settings for rake task
safe: False
lsi: False
username: authoredinexile #github username
repo: authoredinexile.github.io #github repository
branch: master #branch
#relative_source: #source directory
#destination:     #destination directory
production_url:  https://authoredinexile.github.io
source_url: https://github.com/authoredinexile/authoredinexile.github.io #source repository url

favicon_directory: assets/images/favicon
cover: assets/images/main_banner.jpeg
logo: assets/images/logo.png

# Social
facebook: 
twitter: blkwhtrbbt
github: authoredinexile
tumblr: authoredinexile

#Additional Pages
footer_nav:
  about: about
  contact: 
  privacy-policy: 
  copyright: true

left_nav:
  home:
    title: Home
    url:
  about:
    title: About
    url: about
  twwb:
    title: "The Whole World Blind"
    url: twwb
  sting:
    title: Sting
    url: sting

share_social:
  twitter: true
  email: true
  facebook: 
  gplus: 

collections:
  twwb:
    output: true
  sting:
    output: true

#################################
