# Site settings
title: Authored-In-Exile
description: Blog for comics
baseurl: 
url: https://authoredinexile.github.io

favicon_directory: assets/images/favicon
cover: assets/images/main_banner.jpeg
logo: assets/images/logo.png

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: 
twitter: blkwhtrbbt
github: authoredinexile
tumblr: authoredinexile

#Additional Pages
about: about
contact: 
privacy-policy: 

permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: authoredinexile #github username
repo: authoredinexile.github.io #github repository
branch: master #branch
#relative_source: #source directory
#destination: #destination directory
production_url:  https://authoredinexile.github.io
source_url: https://github.com/authoredinexile/authoredinexile.github.io #source repository url

include_copyright: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
